import React, { useState } from "react";
import { Link } from "react-router-dom";
import PlanetDetails from "../Pages/PlanetDetails";
import Timeline from "../Pages/timeline";

export const Jupiter = () => {
  const data = {
    getImageSrc: () => require("../Video/jupiter.mp4"),
    description: `Jupiter is the largest planet in our solar system and the fifth planet from the Sun.Jupiter is a gas giant, primarily composed of hydrogen and helium. It lacks a solid surface and is mostly a massive ball of gas.Jupiter is more massive than all the other planets in the solar system combined, accounting for about 70% of the total planetary mass.The atmosphere of Jupiter is marked by bands of clouds, including the Great Red Spot—a massive storm that has been raging for at least 350 years. The clouds are primarily composed of ammonia and water vapor.Jupiter has a strong magnetic field, much stronger than Earth's. This magnetic field is thought to be generated by the motion of metallic hydrogen in its interior.Jupiter has a faint ring system composed of small, dark particles. The ring system is not as prominent as Saturn's, and it was discovered by the Voyager 1 spacecraft in 1979. Jupiter has 95 moons which makes it the planet with larger number of moons in our solar system.The four largest moons Io, Europa, Ganymede, and Callisto are known as the Galilean moons and were discovered by Galileo Galilei in 1610.Jupiter has a relatively fast rotation, completing one day in about 9.9 Earth hours. However, its orbit around the Sun takes approximately 11.86 Earth years.Moons like Europa and Ganymede, with subsurface oceans, have sparked interest in the possibility of finding life beyond Earth. Scientists are particularly intrigued by the potential habitability of these moons.`,
  };
  const time = [
    {
      date: "Ancient Observations",
      head: "Event One",
      para: `Jupiter has been visible to the naked eye since ancient times and was observed by various cultures. It is one of the five classical planets visible to the naked eye and was known to ancient Babylonian, Greek, and Roman astronomers.`,
    },
    {
      date: "1610",
      head: "Event Two",
      para: `Galileo Galilei, using a telescope he had constructed, discovered the four largest moons of Jupiter, now known as the Galilean moons (Io, Europa, Ganymede, and Callisto).
      `,
    },
    {
      date: "17th century",
      head: "Event Three",
      para: `Italian-French astronomer Jean-Dominique Cassini made important observations of Jupiter's Great Red Spot and its rotation period`,
    },
    {
      date: "1970s and 1980s",
      head: "Event Four",
      para: `NASA's Pioneer 10 and 11, as well as Voyager 1 and 2 spacecraft, conducted flybys of Jupiter, providing close-up images and data about the planet and its moons. These missions offered crucial insights into Jupiter's atmosphere, magnetosphere, and ring system.
      `,
    },
    {
      date: "1995",
      head: "Event Five",
      para: `The Galileo spacecraft became the first spacecraft to enter orbit around Jupiter in 1995. It extensively studied the planet and its moons, including evidence for a subsurface ocean on Europa.`,
    },
    {
      date: "2016",
      head: "Event Six",
      para: `NASA's Juno spacecraft entered orbit around Jupiter, and studied its composition, gravity field, magnetic field, and polar magnetosphere.
      `,
    },
    {
      date: "Recent Discoveries",
      head: "Event Seven",
      para: `Recent observations and analyses, including data from Juno, have revealed new insights into Jupiter's structure, atmospheric dynamics, and magnetic field. The Great Red Spot, a massive storm on Jupiter, has been shrinking, and new storms and features continue to be observed.
      `,
    },
  ];
  const navStyle = {
    backgroundColor: "black",
    color: "white",
    padding: "10px",
  };

  const ulStyle = {
    listStyle: "none",
    padding: "0",
    display: "flex",
    justifyContent: "space-around",
  };

  const liStyle = {
    margin: "0 10px",
    transition: "color 0.3s", // Add a smooth transition for color change
  };
  const linkStyle = {
    textDecoration: "none",
    color: "white",
  };
  const [showPlanetDetails, setShowPlanetDetails] = useState(true);

  const handleAboutClick = () => {
    setShowPlanetDetails(!showPlanetDetails);
    setShowTimeline(false);
  };

  const [showTimeline, setShowTimeline] = useState(false);

  const handleHistoryClick = () => {
    setShowTimeline(!showTimeline);
    setShowPlanetDetails(false);
  };

  return (
    <div style={{ height: "100%" }}>
      <nav style={navStyle}>
        <ul style={ulStyle}>
          <li style={liStyle}>
            <Link
              style={linkStyle}
              className="nav-link"
              onClick={handleAboutClick}
            >
              About
            </Link>
          </li>
          <li style={liStyle}>
            <Link
              style={linkStyle}
              onClick={handleHistoryClick}
              className="nav-link"
            >
              History Overview
            </Link>
          </li>
        </ul>
      </nav>
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        {showPlanetDetails && (
          <PlanetDetails img={data.getImageSrc()} des={data.description} />
        )}
        {showTimeline && <Timeline t={time} />}
      </div>
    </div>
  );
};
export default Jupiter;
